### ISSUE TITLE
RAML's nil value is rendered as string null

### ISSUE THREAD

**Issue by jarrodek** [advanced-rest-client/api-example-generator#1]
In the following example fragment:

```yaml
#%RAML 1.0 NamedExample
TestNull:
  nullValue: null
```
the component renders null as string. The resulting JSON schema is as follows:
```json
{
  "nullValue": "null"
}
```

The correct value should be: 
```json
{
  "nullValue": null
}
```

Jira ref: [APIC-209](https://www.mulesoft.org/jira/browse/APIC-209)
